name: Building Application
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setting Up Nodejs
      uses: actions/setup-node@v3
      with:
        node-version: 23

    - name: Install dependencies
      run: npm install 

    - name: Build the project
      run: npm run build
    
    - name: Upload .next build folder
      uses: actions/upload-artifact@v4
      with:
          name: nextjs-out-folder
          path: .next/

    - name: Commit out folder to repo
      run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add -f out
          git commit -m "Add out folder"
          git push origin main

